import type { Metadata } from 'next';
import { Geist, Geist_Mono, Poppins } from 'next/font/google';

import { CalendarHeader } from '@/feature/calendar/components/CalendarHeader';
import { Card, CardContent } from '@/feature/shared/card';
import AnimationWrapper from '@/feature/shared/animation/AnimationWrapper';

import './globals.css';
import ModalRenderer from '@/feature/shared/modal/ModalRenderer';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['400', '500', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}
      >
        <Card className="w-full max-w-7xl mx-auto mt-6">
          <CardContent>
            <CalendarHeader />
            <AnimationWrapper>{children}</AnimationWrapper>
            <ModalRenderer />
          </CardContent>
        </Card>
      </body>
    </html>
  );
}
